
from collections import deque
from pathlib import Path

import numpy as np


API_URL = "https://api.genome.ucsc.edu/getData/sequence" # UCSC REST API for fetching genomic sequences
OBS_LIMIT = None                                         # max observations read from FASTA (None = whole file)
_BASES = ["A", "T", "C", "G"]

ASSEMBLY = "hs1"  # T2T-CHM13 v2.0


# Approximate euchromatic MSY boundaries.
# - PAR1 end  -> start of euchromatic MSY
# - Yq12 het. -> end of euchromatic MSY
# NOTE: the centromere lies inside this interval; in hg19 it is a gap (Ns),
REGIONS = {
    "hs1": {            # T2T-CHM13 v2.0
        "chrom": "chrY",
        "start": 2_458_320,   # end of PAR1 (Rhie et al. 2023)
        "end":   26_673_214,  # start of Yq12 heterochromatin
        "label": "T2T-CHM13v2.0_chrY_euchromatic_MSY",
    },
}

#! -------------------------------------------------------------
#!
#! UTILITIES, maybe I'll need to create a library fire for these
#!
#! -------------------------------------------------------------


def _read_obs_gene(fasta_path: Path, limit: int | None = None) -> np.ndarray:
    reader = FastaReader(fasta_path, symbols=_BASES)
    obs = reader.read()
    if limit is not None:
        obs = obs[:limit]
    return obs.astype(int)


def write_gene(states: np.ndarray, fasta_path: Path, out_path: Path) -> None:

    with open(out_path, "w") as f:
        f.write(f"# Gene structure predictions | source: {fasta_path.name} | generated by tensor-viterbi\n")
        flat = states.astype(int)
        for i in range(0, len(flat), 30):
            f.write("".join(str(s) for s in flat[i:i + 30]) + "\n")


def fetch_sequence(genome: str, chrom: str, start: int, end: int) -> str:

    params = {"genome": genome, "chrom": chrom, "start": start, "end": end}
    print(f"[info] Requesting {chrom}:{start}-{end} from {genome} ...",
          file=sys.stderr)
    r = requests.get(API_URL, params=params, timeout=300)
    r.raise_for_status()
    data = r.json()
    if "dna" not in data:
        raise RuntimeError(f"Unexpected response: {data}")
    return data["dna"]


def write_fasta(path: Path, header: str, sequence: str, width: int = 60) -> None:
    """Write a single-record FASTA, wrapping the sequence at `width` columns."""
    with path.open("w") as fh:
        fh.write(f">{header}\n")
        for line in textwrap.wrap(sequence, width=width):
            fh.write(line + "\n")




class FastaReader:
    """Read a FASTA file and map nucleotides to observation indices.

    Symbols must be defined before reading so the mapping is fixed.
    Characters not in the symbol set are skipped silently.

    Parameters
    ----------
    path:
        Path to the .fa / .fasta file.
    symbols:
        Ordered list of valid characters (e.g. ["A","C","G","T","N"]).
        Position in the list is the observation index passed to the model.
        Matching is case-insensitive.
    """

    def __init__(self, path: str | Path, symbols: list[str]):
        self._path = Path(path)
        self.symbols = symbols
        self._index: dict[str, int] = {s.upper(): i for i, s in enumerate(symbols)}

    # ------------------------------------------------------------------
    # Core generator — skips headers and unknown characters
    # ------------------------------------------------------------------

    def _iter_indices(self):
        with open(self._path) as f:
            for line in f:
                if line.startswith(">"):
                    continue
                for ch in line.rstrip():
                    idx = self._index.get(ch.upper())
                    if idx is not None:
                        yield idx

    # ------------------------------------------------------------------
    # Public reading API
    # ------------------------------------------------------------------

    def read(self) -> np.ndarray:
        """Load the entire sequence as a numpy array of observation indices."""
        return np.fromiter(self._iter_indices(), dtype=np.int64)

    def iter_chars(self):
        """Yield one observation index at a time (memory-efficient)."""
        yield from self._iter_indices()

    def iter_windows(self, k: int):
        """Yield sliding windows of length k (step=1) as int64 arrays."""
        if k < 1:
            raise ValueError(f"Window size must be >= 1, got {k}")
        buf = deque()
        for idx in self._iter_indices():
            buf.append(idx)
            if len(buf) == k:
                yield np.array(buf, dtype=np.int64)
                buf.popleft()

