#!/usr/bin/env python3
"""CpG island detection over chrY's euchromatic MSY region (T2T-CHM13 v2.0),
via a single Viterbi decoding pass on the native OpenMP backend.
"""

import time
from pathlib import Path

import numpy as np

from tensor_viterbi import HSMM
from tensor_viterbi.viterbi import decode_tensor_viterbi_omp
from modules.genomics import UCSCRegion, FastaReader, DNA_BASES, fetch_cpg_ground_truth

# k-mer size the model reads the FASTA with (k=2 -> dinucleotides).
K = 2


def build_cpg_hsmm(obs_seq: np.ndarray) -> HSMM:

    # HSMM model definition for CpG island detection: two states (Background,
    # CpG-island), read as dinucleotides (k=2) since the defining feature of a
    # CpG island isn't just GC content but the CG dinucleotide itself — genome-wide
    # it's strongly suppressed (methylated C deaminates to T over evolutionary
    # time), while inside CpG islands that suppression is absent (unmethylated).
    STATES = ["Background", "CpG-island"]

    # Dinucleotide emission probabilities per state, each summing to 1.
    # Background: bulk genomic composition (30% A/T, 20% C/G) with CG suppressed
    # to ~1/4 of its naive frequency. CpG-island: C/G-enriched (35% C/G) with CG
    # left unsuppressed and then some.
    BACKGROUND_EMIT = {
        "AA": 0.092784, "AT": 0.092784, "AC": 0.061856, "AG": 0.061856,
        "TA": 0.092784, "TT": 0.092784, "TC": 0.061856, "TG": 0.061856,
        "CA": 0.061856, "CT": 0.061856, "CC": 0.041237, "CG": 0.010309,
        "GA": 0.061856, "GT": 0.061856, "GC": 0.041237, "GG": 0.041237,
    }
    ISLAND_EMIT = {
        "AA": 0.021201, "AT": 0.021201, "AC": 0.049470, "AG": 0.049470,
        "TA": 0.021201, "TT": 0.021201, "TC": 0.049470, "TG": 0.049470,
        "CA": 0.049470, "CT": 0.049470, "CC": 0.115430, "CG": 0.173145,
        "GA": 0.049470, "GT": 0.049470, "GC": 0.115430, "GG": 0.115430,
    }

    MAX_DURATION = 1000  # uniform 1/D per state


    N = len(STATES)
    emissions = [a + b for a in DNA_BASES for b in DNA_BASES]
    emission_probs = np.array([
        [BACKGROUND_EMIT[dinuc], ISLAND_EMIT[dinuc]] for dinuc in emissions
    ])

    duration_probs = np.full((MAX_DURATION, N), 1.0 / MAX_DURATION)
    trans_mat = np.full((N, N), 1.0 / N)
    start_probs = np.full(N, 1.0 / N)

    return (
        HSMM(STATES)
        .set_emissions(emissions, emission_probs)
        .set_transitions(trans_mat)
        .set_duration_probs(duration_probs)
        .set_start_probs(start_probs)
        .set_observations(obs_seq)
    )



#! NON MI CONVINCE, SEMBRA MOLTO DIVERSO
def score_against_ground_truth(predicted: np.ndarray, ground_truth: np.ndarray) -> float:
    """Fraction of positions where `predicted` (decoded 0/1 states) agrees with
    `ground_truth` (UCSC's own CpG-island calls, same 0/1 notation). The two
    are truncated to the shorter length first, since `predicted` is indexed by
    dinucleotide start (k=2) while `ground_truth` is indexed per base."""
    n = min(len(predicted), len(ground_truth))
    return float(np.mean(predicted[:n] == ground_truth[:n]))


def write_islands(states: np.ndarray, fasta_path: Path, out_path: Path) -> None:
    with open(out_path, "w") as f:
        f.write(f"# CpG island predictions | source: {fasta_path.name} | generated by tensor-viterbi\n")
        flat = states.astype(int)
        for i in range(0, len(flat), 30):
            f.write("".join(str(s) for s in flat[i:i + 30]) + "\n")


def main() -> None:

    #! ----- FASTA DOWNLOAD ----- 
    dna_region = UCSCRegion(
        assembly="hs1",
        chrom="chrY",
        start=2_458_320,   # end of PAR1 (Rhie et al. 2023)
        end=26_673_214,     # start of Yq12 heterochromatin
        label="T2T-CHM13v2.0_chrY_euchromatic_MSY",
    )
    OBS_LIMIT = None  # max observations read from FASTA (None = whole file)
    fasta_path = dna_region.download()

    print(f"Loading {fasta_path} ...")

    obs_seq = FastaReader(fasta_path, symbols=DNA_BASES, k=K).read()
    if OBS_LIMIT is not None:
        obs_seq = obs_seq[:OBS_LIMIT]
    #! ----- FASTA DOWNLOAD -----


    #! ----- BUILD HSMM -----
    cpg_hsmm = build_cpg_hsmm(obs_seq)
    cpg_hsmm.print_model()
    #! ----- BUILD HSMM -----


    #! ----- VITERBI DECODING -----
    t0 = time.perf_counter()
    result = decode_tensor_viterbi_omp(
        cpg_hsmm.N, cpg_hsmm.trans_mat, cpg_hsmm.emission_probs,
        cpg_hsmm.duration_probs_linear, cpg_hsmm.start_probs,
        cpg_hsmm.duration_probs, cpg_hsmm.obs_seq,
    )
    elapsed = time.perf_counter() - t0

    out_path = fasta_path.with_suffix(".cpg")

    #* SPECIFIC OF CPG ISLANDS, I SHOULD FIND A MORE GENERAL WAY TO WRITE THE RESULTS
    n_background = int(np.sum(result == 0))
    n_island     = int(np.sum(result == 1))
    print(f"-> decode time={elapsed:.4f} s  Background={n_background} ({100*n_background/cpg_hsmm.T:.2f}%)  "
            f"CpG-island={n_island} ({100*n_island/cpg_hsmm.T:.2f}%)")
    #! ----- VITERBI DECODING -----


    #! ----- UCSC GROUND TRUTH COMPARISON -----
    ground_truth = fetch_cpg_ground_truth(dna_region)
    score = score_against_ground_truth(result, ground_truth)
    print(f"-> agreement with UCSC '{dna_region.chrom}' cpgIslandExt = {100*score:.2f}%")
    #! ----- UCSC GROUND TRUTH COMPARISON -----

    write_islands(result, fasta_path, out_path)
    print(f"\nResult written -> {out_path}")


if __name__ == "__main__":
    main()
