#!/usr/bin/env python3
"""CpG island detection over chrY's euchromatic MSY region (T2T-CHM13 v2.0),
via a single Viterbi decoding pass on the native OpenMP backend.
"""

import time
from pathlib import Path

import numpy as np
import yaml

from tensor_viterbi import HSMM
from tensor_viterbi.viterbi import decode_tensor_viterbi_omp
from modules.genomics import UCSCRegion, FastaReader, DNA_BASES

MODEL_CONFIG_PATH = Path(__file__).parent / "cpg_islands_model.yaml"


def load_model_config(path: str | Path = MODEL_CONFIG_PATH) -> dict:
    """Read the HSMM model definition (states, emissions, duration, ...) from YAML."""
    with open(path) as f:
        return yaml.safe_load(f)


def _dinucleotide_emit(marginal: np.ndarray, cg_factor: float) -> np.ndarray:
    """Expand a per-base marginal into a 16-symbol dinucleotide distribution
    (index = i*len(BASES) + j for dinucleotide BASES[i]+BASES[j]), nudging
    the CG entry by `cg_factor` before renormalizing."""
    probs = np.outer(marginal, marginal).flatten()  # independent (expected) dinucleotide probs
    cg_index = DNA_BASES.index("C") * len(DNA_BASES) + DNA_BASES.index("G")
    probs[cg_index] *= cg_factor
    return probs / probs.sum()


def build_cpg_hsmm(obs_seq: np.ndarray, cfg: dict | None = None) -> HSMM:
    """Build the CpG-island HSMM from a config dict, as returned by `load_model_config()`.

    The config carries the same things this function used to hardcode:
    states, per-state base marginal composition, CG dinucleotide
    suppression/enrichment factors (k=2 only), max duration, and optionally
    transitions/start probabilities. See cpg_islands_model.yaml.
    """
    if cfg is None:
        cfg = load_model_config()

    states = cfg["states"]
    N = len(states)
    if N != 2:
        raise ValueError(
            f"build_cpg_hsmm's config is fixed to exactly 2 states "
            f"(background_marginal/island_marginal), got {N}: {states}"
        )
    k = cfg.get("k", 1)
    emissions_cfg = cfg["emissions"]

    if k == 1:
        emissions = DNA_BASES
        emission_probs = np.column_stack([
            np.array(emissions_cfg["background_marginal"], dtype=float),
            np.array(emissions_cfg["island_marginal"], dtype=float),
        ])
    elif k == 2:
        background_marginal = np.array(emissions_cfg["background_marginal"], dtype=float)
        island_marginal     = np.array(emissions_cfg["island_marginal"], dtype=float)
        emissions = [a + b for a in DNA_BASES for b in DNA_BASES]
        background_emit = _dinucleotide_emit(background_marginal, emissions_cfg["cg_suppression_background"])
        island_emit      = _dinucleotide_emit(island_marginal, emissions_cfg["cg_enrichment_island"])
        emission_probs = np.column_stack([background_emit, island_emit])
    else:
        raise ValueError(f"k={k} not supported by build_cpg_hsmm (only 1 or 2)")

    D = cfg["duration"]["D"]
    duration_probs = np.full((D, N), 1.0 / D)

    trans_mat = (np.array(cfg["transitions"], dtype=float) if "transitions" in cfg
                 else np.full((N, N), 1.0 / N))
    start_probs = (np.array(cfg["start_probs"], dtype=float) if "start_probs" in cfg
                   else np.full(N, 1.0 / N))

    return (
        HSMM(states)
        .set_emissions(emissions, emission_probs)
        .set_transitions(trans_mat)
        .set_duration_probs(duration_probs)
        .set_start_probs(start_probs)
        .set_observations(obs_seq)
    )


def write_islands(states: np.ndarray, fasta_path: Path, out_path: Path) -> None:
    with open(out_path, "w") as f:
        f.write(f"# CpG island predictions | source: {fasta_path.name} | generated by tensor-viterbi\n")
        flat = states.astype(int)
        for i in range(0, len(flat), 30):
            f.write("".join(str(s) for s in flat[i:i + 30]) + "\n")


def main() -> None:

    cfg = load_model_config()
    K = cfg.get("k", 1)  # k-mer size to read the FASTA with, driven by the same YAML

    dna_region = UCSCRegion(
        assembly="hs1",
        chrom="chrY",
        start=2_458_320,   # end of PAR1 (Rhie et al. 2023)
        end=26_673_214,     # start of Yq12 heterochromatin
        label="T2T-CHM13v2.0_chrY_euchromatic_MSY",
    )
    OBS_LIMIT = None  # max observations read from FASTA (None = whole file)


    fasta_path = dna_region.download()

    print(f"Loading {fasta_path} ...")

    obs_seq = FastaReader(fasta_path, symbols=DNA_BASES, k=K).read()
    if OBS_LIMIT is not None:
        obs_seq = obs_seq[:OBS_LIMIT]

    cpg_hsmm = build_cpg_hsmm(obs_seq, cfg)

    #! Whe should create an heuristic function check that verifies that the observations set declared
    #! are compatible with the sequence.

    N = len(cpg_hsmm.states)
    T = len(cpg_hsmm.obs_seq)
    D = cpg_hsmm.duration_probs_linear.shape[0]
    print(f"states (N)={N}, timesteps (T)={T}, max duration (D)={D}\n")

    cpg_hsmm.print_model()

    t0 = time.perf_counter()
    result = decode_tensor_viterbi_omp(
        N, cpg_hsmm.trans_mat, cpg_hsmm.emission_probs,
        cpg_hsmm.duration_probs_linear, cpg_hsmm.start_probs,
        cpg_hsmm.duration_probs, cpg_hsmm.obs_seq,
    )
    elapsed = time.perf_counter() - t0

    out_path = fasta_path.with_suffix(".cpg")

    #* SPECIFIC OF CPG ISLANDS, I SHOULD FIND A MORE GENERAL WAY TO WRITE THE RESULTS
    n_background = int(np.sum(result == 0))
    n_island     = int(np.sum(result == 1))
    print(f"-> decode time={elapsed:.4f} s  Background={n_background} ({100*n_background/T:.2f}%)  "
            f"CpG-island={n_island} ({100*n_island/T:.2f}%)")

    write_islands(result, fasta_path, out_path)
    print(f"\nResult written -> {out_path}")


if __name__ == "__main__":
    main()
